### ISSUE TITLE
Distillation of Resnet-50 backbone on BDD100K

### ISSUE THREAD

**Issue by AmanGoyal99** [yzd-v/FGD#1]
Greetings,

This is Aman Goyal. I am currently pursuing research at CMU and MSU. I wanted to know if it is possible to perform distillation of Resnet-50 backbone on BDD100K dataset through your codebase.

Thanks

**Comment by yzd-v** [comment]
Yes, you may change the related setting about the dataset if you use mmdetection. Or you can apply FGD method to your own code according to this repo and paper.
