### ISSUE TITLE
In line 152 and 153, should it be `S_s` and `C_s` instead of `S_t` and `C_t`?

### ISSUE THREAD

**Issue by ZHANGHeng19931123** [yzd-v/FGD#12]
https://github.com/yzd-v/FGD/blob/7cdd34e8d59d94dd21c3cac5e2398d9464151515/mmdet/distillation/losses/fgd.py#L152

**Comment by yzd-v** [comment]
In the paper, we use teacher's attention to guide the student. So here is S_t and C_t.

**Comment by forever10086** [comment]
你好，[这个](https://github1s.com/yzd-v/FGD/blob/master/mmdet/distillation/losses/fgd.py#L44-L55)是否也是出于这样的考虑？
