### ISSUE TITLE
训练过程没办法评估

### ISSUE THREAD

**Issue by Cuibaby** [yzd-v/FGD#14]
你好，我想在你的代码再增加一个teacher，就是两个teacher，其中一个teacher有自己优化器，参数要更新，请问这种方式怎么修改？基于你的代码修改了一下，目前我采用的共用一个优化器，但是训练中没法测试，请问你的代码在训练时能够正常测试吗？还是先把权重转换成mmdet格式再测试？

**Comment by yzd-v** [comment]
可以参考https://github.com/yzd-v/FGD/blob/7a927937f41ca4d71d839b0696dafc60e7d4ec2b/mmdet/distillation/distillers/detection_distiller.py#L80和https://github.com/yzd-v/FGD/blob/7a927937f41ca4d71d839b0696dafc60e7d4ec2b/mmdet/distillation/distillers/detection_distiller.py#L158根据需求进行对应的修改
