### ISSUE TITLE
the result of FGD on yolov5

### ISSUE THREAD

**Issue by guxiaowei1** [yzd-v/FGD#15]
The conclusion of this paper is fascinating，so i apply FGD to yolov5 on my dataset.
But, the performance dropped a lot， which makes me confused. 
If I have a chance, would you please communicate with me. thank u for your replying

**Comment by yzd-v** [comment]
We can talk about it.

**Comment by WainBK** [comment]
> The conclusion of this paper is fascinating，so i apply FGD to yolov5 on my dataset. But, the performance dropped a lot， which makes me confused. If I have a chance, would you please communicate with me. thank u for your nihaoqingwen 


Hello,how you configure the distillation model of yolov5? is it convenient for you to tell me?
