### ISSUE TITLE
I think the Get_FEA_loss calculation code has some question

### ISSUE THREAD

**Issue by chaochao1993** [yzd-v/FGD#17]
your code of  Get_FEA_loss calculation is that:
fea_t = torch.mul(preds_T, torch.sqrt(S_t))
fea_t = torch.mul(fea_t, torch.sqrt(C_t))
fea_s = torch.mul(preds_s, torch.sqrt(S_t))
fea_s = torch.mul(fea_s, torch.sqrt(C_t))
I think  the Get_FEA_loss calculation's is that 
fea_t = torch.mul(preds_T, torch.sqrt(S_t))
fea_t = torch.mul(fea_t, torch.sqrt(C_t))
fea_s = torch.mul(preds_s, torch.sqrt(S_s))
fea_s = torch.mul(fea_s, torch.sqrt(C_s))
this is just my guess, I hope you give me the answer

**Comment by yzd-v** [comment]
You can refer the paper and the issue: https://github.com/yzd-v/FGD/issues/12
