### ISSUE TITLE
GCNet vs. Non-Local module

### ISSUE THREAD

**Issue by Senwang98** [yzd-v/FGD#2]
@yzd-v 
Hi, thanks for your simple and powerfull KD method. I have one question, why use GCNet rather commonly used Non-local module,   
Have you test these two OPs since GCNet is little better than Non-local.(Maybe some experiments about these two modules can be added into your paper, since this is one question reviewers intuitively will ask)

**Comment by yzd-v** [comment]
Both GCNet and non-local can be used to add global knowledge for distillation. And we compare them in ablation study. The lighter GCNet is easier to train for distillation.

**Comment by Senwang98** [comment]
@yzd-v 
Okay, I have seen Table 6. in your paper. 
![image](https://user-images.githubusercontent.com/23122139/143998704-6a1e2edb-ede2-4da3-b14f-aa368f0a81af.png)
However, in this way, FGD's strength maybe weaken.
As is shown in FKD's paper Table 3. FKD (Non-local) can get the same performance as yours when using GCblock.
![image](https://user-images.githubusercontent.com/23122139/144000390-374cc98c-4267-425d-9fd0-2de2a4826ef3.png)

**Comment by yzd-v** [comment]
You may read the two papers carefully. In table 6, we just use global distillation without focal distillation. While the result in FKD is achieved with all losses. However, Faster RCNN can achieve 42.0 mAP with focal and global distillation together.

**Comment by Senwang98** [comment]
@yzd-v 
Ok, it's my fault(feel a bit embarrassed, I will delete above pictures......23333)
