### ISSUE TITLE
init_cfg and pretrained cannot be specified at the same time

### ISSUE THREAD

**Issue by eilenelxc** [yzd-v/FGD#27]
![image](https://user-images.githubusercontent.com/66711541/165762848-0e942053-a964-4820-8752-0dc2b57a0fca.png)

**Comment by yzd-v** [comment]
This is caused by the different strategies to initialize the backbone for different mmdet versions. I've fixed this problem, you can refer the new FCOS config in https://github.com/yzd-v/FGD/blob/master/configs/fcos/fcos_center-normbbox-giou_r50_caffe_fpn_gn-head_mstrain_1x_coco.py

**Comment by eilenelxc** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by eilenelxc** [comment]
Thank you for your reply, I really appreciate it!
