### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'maximum'

### ISSUE THREAD

**Issue by DanceInDark** [yzd-v/FGD#31]
Hi，I try to run the code bug get this error: AttributeError: module 'torch' has no attribute 'maximum'.

**Comment by yzd-v** [comment]
You may change your Pytorch version or try to use torch.max().

**Comment by DanceInDark** [comment]
> You may change your Pytorch version or try to use torch.max().
可以放一个依赖包的版本列表吗

**Comment by yzd-v** [comment]
相比于mmdetection，并不需要额外的包，能跑mmdet就能适配fgd。你的pytorch不支持torch.maximum的话，可以选择变到torch==1.7或者有这个函数的其他版本，或者修改使用torch.max()来完成
