### ISSUE TITLE
the result of solov2 model after distiller is reduced

### ISSUE THREAD

**Issue by Evoluange** [yzd-v/FGD#35]
Hi,Thanks your great work
I use FDG  in solov2, the teacher model is solov2-resNet101 and the student model is solov2-mobileNetV2
the train log is below:
[20220520_164942.log](https://github.com/yzd-v/FGD/files/8753584/20220520_164942.log)
and the config file is below:
[fgd_solov2_r101_c8_ms_distill_solov2_mobileNetV2_slim_c8_txt.txt](https://github.com/yzd-v/FGD/files/8753647/fgd_solov2_r101_c8_ms_distill_solov2_mobileNetV2_slim_c8_txt.txt)
I compared the mAP between solov2-mobileNetV2 distiller model  and no distiller model, but the result is not ideal.
the mAP of solov2-mobileNetV2 model (0.465) ,which is higher than the distiller model (0.426)
why the accuary of the distiller model reduced ?

**Comment by yzd-v** [comment]
It seems your teacher doesn't load the weight exactly. Besides, the inheriting strategy seems wrong either. You can refer this setting.
<img width="538" alt="截屏2022-05-23 下午6 34 39" src="https://user-images.githubusercontent.com/54797851/169801156-64f971d7-a736-4a3f-ab21-2c8d07f075a3.png">

**Comment by Evoluange** [comment]
You mean the teacher model didn't load success from the beginning, what's wrong in inheriting strategy?
The teacher model was trained by myself  before distiller , the config file is below:
[solov2_r101_fpn_3x_c8_twoc.txt](https://github.com/yzd-v/FGD/files/8754513/solov2_r101_fpn_3x_c8_twoc.txt)
I change the mobileNetV2 backbone channel from 2048 to 320 in student model in order to slim the model .

**Comment by yzd-v** [comment]
How do you write the code in this part?
![image](https://user-images.githubusercontent.com/54797851/169821554-a07cfb5d-99f4-490b-ab95-8e560f50422e.png)

**Comment by Evoluange** [comment]
`        if init_student:
            print(teacher_pretrained)
            t_checkpoint = _load_checkpoint(teacher_pretrained)
            all_name = []
            for name, v in t_checkpoint["state_dict"].items():
                if name.startswith("backbone."):
                    continue
                else:
                    all_name.append((name, v))

            state_dict = OrderedDict(all_name)
            load_state_dict(self.student, state_dict)
`
I follow your code in mmdet/distillation/distillers/detection_distiller.py

**Comment by Evoluange** [comment]
![image](https://user-images.githubusercontent.com/25747262/169822952-f21e2b26-8ea5-4b60-83fe-649d6979648f.png)
I follow your code in mmdet/distillation/distillers/detection_distiller.py

**Comment by Evoluange** [comment]
![image](https://user-images.githubusercontent.com/25747262/169823193-d07161f3-8de2-4eee-b595-bcf04c156d0a.png)
The code in mmdet/distillation/distillers/detection_distiller.py, I am not change.

**Comment by yzd-v** [comment]
You use mmdet==2.24, so you should add self.student.init_weights() in mmdet/distillation/distiller.py. Besides, you don't need model.init_weights() in tools/train.py for distiller.

**Comment by Evoluange** [comment]
OK, I do use mmdet==2.24. I have revised these two lines and train agin. Thank you so much again.
