### ISSUE TITLE
Why can't I reproduce the accuracy of the paper according to the experimental settings given by your code?

### ISSUE THREAD

**Issue by shaoshitong** [yzd-v/FGD#36]
I did the distillation of fgd_retina_rx101_64x4d_distill_retina_r50_fpn_2x_coco according to the settings in the paper, but the accuracy is lower than the baseline. I don't understand why this result occurs?
[20220527_173012.log](https://github.com/yzd-v/FGD/files/8802057/20220527_173012.log)

**Comment by yzd-v** [comment]
You use mmdet==2.24, so you should add self.student.init_weights() in mmdet/distillation/distiller.py. Besides, you don't need model.init_weights() in tools/train.py for distiller. You can refer this [issue](https://github.com/yzd-v/FGD/issues/35) or  this repo [MGD](https://github.com/yzd-v/MGD)
