### ISSUE TITLE
yolox

### ISSUE THREAD

**Issue by Veiiling** [yzd-v/FGD#40]
HI, about yolox, can you update the config? i am tring fgd in yolox-tiny, but for ap50, it only improved 0.1%, could you give some suggestions?

**Comment by yzd-v** [comment]
Yolox-tiny has been fully trained, it is hard to benefit it more with distillation.

**Comment by Veiiling** [comment]
> 

Thank you for your reply. If I use Yolo-small as a student model, YOLOX-x as teacher model, will it be improved? And the student network of distillation training from scratch?

**Comment by yzd-v** [comment]
You can have a try.

**Comment by lixiangMindSpore** [comment]
> HI, about yolox, can you update the config? i am tring fgd in yolox-tiny, but for ap50, it only improved 0.1%, could you give some suggestions?

How to modify FGD to run yolox-tiny with yolox-l as the teather?  In FGD/configs/distillers/fgd, I can't find the config of yolox.
Thank you so much!
