### ISSUE TITLE
Missing keys of ckpt

### ISSUE THREAD

**Issue by JwFbupt** [yzd-v/FGD#46]
Hi,
      Thank you for sharing your codes
      The program throw warnings, when loading the checkpoint as:
![Screenshot 2022-07-28 180119](https://user-images.githubusercontent.com/49198978/181479864-0cb05da0-8721-4be2-8e65-6a7a9a10f3cf.png)

   Are there any problems when we merge the codes?

**Comment by JwFbupt** [comment]
Yet, we have alter the code in detection_distiller.py.

**Comment by yzd-v** [comment]
This problem happens for training or testing? If training, which config?

**Comment by JwFbupt** [comment]
The problem happens in training stage. The problem happens in this line in detetion_distiller.py: 
                load_state_dict(self.student, state_dict
![3711659012355_ pic](https://user-images.githubusercontent.com/49198978/181508386-1f6e0c8c-266d-4182-8761-fbc929c33d7e.jpg)
)

**Comment by yzd-v** [comment]
Ok. It's fine. Beacuse we just use teacher's neck and head to initialize the student.
