### ISSUE TITLE
How to modify FGD to run yolox-s with yolox-l as the teather?

### ISSUE THREAD

**Issue by lixiangMindSpore** [yzd-v/FGD#47]
How to modify FGD to run yolox-tiny with yolox-l as the teather? In FGD/configs/distillers/fgd, I can't find the config of yolox.
Thank you so much!

**Comment by yzd-v** [comment]
Please read README. The config is in branch yolox. Besides, Yolox-tiny has been fully trained, it is hard to benefit it more with distillation
