### ISSUE TITLE
No module named 'mmdet.distillation'

### ISSUE THREAD

**Issue by lixiangMindSpore** [yzd-v/FGD#49]
源代码，mmdet==2.11.0，mmcv-full==1.2.4，运行出现如下图所示问题，请问这个怎么解决？
![image](https://user-images.githubusercontent.com/78945582/183384008-8ea56d88-cdaa-4810-ae36-b5fc82937842.png)

**Comment by yzd-v** [comment]
看起来像是你的运行指令或者python路径不对，你可以先跑通不蒸馏mmdet自身试试

**Comment by lixiangMindSpore** [comment]
> 看起来像是你的运行指令或者python路径不对，你可以先跑通不蒸馏mmdet自身试试

在容器里跑的，创建容器时添加--gpus all，没有报错误No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'，只有下图所示错误
![image](https://user-images.githubusercontent.com/78945582/183541662-cd63f5f1-f467-4dfa-8fe0-a6336dacdd76.png)

**Comment by yzd-v** [comment]
这是你没配置好mmdetection的问题，你可以去mmdet的源repo下寻求帮助，我只能帮你解决关于FGD的问题
