### ISSUE TITLE
About result

### ISSUE THREAD

**Issue by peiyingxin** [yzd-v/FGD#50]
Hi, I have run 
fgd_faster_rcnn_r101_fpn_2x_distill_faster_rcnn_r50_fpn_2x_coco.py
for 24 epochs, using batch size == 4*8, I get mAP 0.405 for faster_rcnn_r50_fpn_2x_coco.
In your benchmark I found faster_rcnn_r50_fpn_2x_coco upto 0.420, I want to know your training config, teacher resnet 101 and student resnet 50?

**Comment by yzd-v** [comment]
You can read the paper to know the details.
