### ISSUE TITLE
fgd_yoloxl_distill_yoloxm_coco.py中的FGDLoss就是fgd_solo_r101_ms_distill_solo_r50_coco.py中的FeatureLoss吗？

### ISSUE THREAD

**Issue by lixiangMindSpore** [yzd-v/FGD#51]
fgd_yoloxl_distill_yoloxm_coco.py中的FGDLoss就是fgd_solo_r101_ms_distill_solo_r50_coco.py中的FeatureLoss吗？
![image](https://user-images.githubusercontent.com/78945582/183859661-ed1f2ac7-6233-4033-9a38-29673be0e3ab.png)
![image](https://user-images.githubusercontent.com/78945582/183859801-dce12095-e599-4cf2-9188-5716760cfcd1.png)

**Comment by yzd-v** [comment]
这里是我写错了，FGDLoss应该改成FeatureLoss，两个是一样的，我一会更新修改一下这

**Comment by peiyingxin** [comment]
> fgd_yoloxl_distill_yoloxm_coco.py中的FGDLoss就是fgd_solo_r101_ms_distill_solo_r50_coco.py中的FeatureLoss吗？ ![image](https://user-images.githubusercontent.com/78945582/183859661-ed1f2ac7-6233-4033-9a38-29673be0e3ab.png) ![image](https://user-images.githubusercontent.com/78945582/183859801-dce12095-e599-4cf2-9188-5716760cfcd1.png)

铁汁，你跑出结果了吗？
