### ISSUE TITLE
About the cfg distillation for yolox

### ISSUE THREAD

**Issue by Errol-golang** [yzd-v/FGD#53]
Can you please provide the code of distillation from Yolox-l to Yolox-m?

**Comment by Errol-golang** [comment]
I mean the distillation config file from the yolox-l to yolox-m

**Comment by peiyingxin** [comment]
> I mean the distillation config file from the yolox-l to yolox-m

Author had commit yolox code, git checkout -b yolox.

**Comment by yzd-v** [comment]
> I mean the distillation config file from the yolox-l to yolox-m

Please refer README. It is in branch yolox.

**Comment by Errol-golang** [comment]
> > I mean the distillation config file from the yolox-l to yolox-m
> 
> Please refer README. It is in branch yolox.

Thanks. I found that.

**Comment by Errol-golang** [comment]
> > I mean the distillation config file from the yolox-l to yolox-m
> 
> Author had commit yolox code, git checkout -b yolox.

Thanks. I've noticed.
