### ISSUE TITLE
Hyper-parameter settings on ablation study

### ISSUE THREAD

**Issue by JwFbupt** [yzd-v/FGD#56]
Thank you so much for your contribution. 
I wonder your hyper-parameters setting on your ablation study in Table 4.

![image](https://user-images.githubusercontent.com/49198978/185575756-1f94ff1c-b186-47da-9d7f-b672cdc8721b.png)

Specifically, what is the coef of relation loss (global distillation) when you only use global distillation

**Comment by yzd-v** [comment]
It's the same as the final coef.
