### ISSUE TITLE
实验数据是否有误？感谢

### ISSUE THREAD

**Issue by renyu-renyu** [yzd-v/FGD#58]
![image](https://user-images.githubusercontent.com/88662555/188306568-a68516e0-5ed7-4347-a9df-ddceceeec641.png)

**Comment by yzd-v** [comment]
应该是没错的，很多同学都复现了这个结果，有什么问题吗

**Comment by renyu-renyu** [comment]
最后的数值好像是算错了吧。平均不对啊。还是



| |
18741275118
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年09月04日 17:44 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [yzd-v/FGD] 实验数据是否有误？感谢 (Issue #58) |

应该是没错的，很多同学都复现了这个结果，有什么问题吗

**Comment by renyu-renyu** [comment]
> 

最后的数值好像是算错了吧。平均不对啊。还是

**Comment by yzd-v** [comment]
没懂你的意思，mAP不是那三个算算术平均
![image](https://user-images.githubusercontent.com/54797851/188309036-7ef714dd-e9af-4c12-b802-91e3bf10da7a.png)
