### ISSUE TITLE
FCOS实验结果问题

### ISSUE THREAD

**Issue by changxin111** [yzd-v/FGD#60]
作者你好，我尝试复现你论文中的FCOS-Res101蒸馏FCOS-Res50，论文中为42.7
我跑了两次结果都为39.2左右，可以帮我看下问题出在哪里吗
我的配置是bs为4x4，lr为0.01，由于服务器限制，训练所需模型都预先下好并导入的
[fgd-fcos.log](https://github.com/yzd-v/FGD/files/9598124/fgd-fcos.log)

**Comment by yzd-v** [comment]
你的老师的weight没有正确加载

**Comment by changxin111** [comment]
请问这个问题要怎么解决呢？我没修改代码的其他部分，预训练模型也是按照网址直接下的。

**Comment by yzd-v** [comment]
感觉你的代码有点问题呀，你看log里加载老师时的weight，写的是load from fcos_r50_caffe_fpn_gn-head_1x_coco-821213aa.pth

**Comment by yzd-v** [comment]
哦 应该是fcos的初始化问题，你clone的是我很早的config，那个pretrained应该改到backbone的init里。你重新改一下student的config就行，我更新过的

**Comment by changxin111** [comment]
我又重新看了一下我修改的部分，有可能是我模型下载导入错了，
不应该是fcos_r50_caffe_fpn_gn-head_1x_coco，应该是resnet50_caffe
明天我重新跑一下看看，非常感谢你的解答
