### ISSUE TITLE
what does it  means

### ISSUE THREAD

**Issue by baibaidedongdong** [yzd-v/FGD#61]
Hi, what does it mean? Waitting for your reply，thank you.
`        

      for item_loc in distill_cfg:
            student_module = 'student_' + item_loc.student_module.replace('.','_')
            teacher_module = 'teacher_' + item_loc.teacher_module.replace('.','_')

            self.register_buffer(student_module,None)
            self.register_buffer(teacher_module,None)

            hook_teacher_forward,hook_student_forward = regitster_hooks(student_module ,teacher_module )
            teacher_modules[item_loc.teacher_module].register_forward_hook(hook_teacher_forward)
            student_modules[item_loc.student_module].register_forward_hook(hook_student_forward)`

**Comment by yzd-v** [comment]
Save the feature ussing a hook. So we can get student and teacher's feature according to the name. Besides, you can also get the feature with another way. You can refer the [cls](https://github.com/yzd-v/MGD/blob/master/cls/mmcls/distillation/distillers/classification_distiller.py) in [MGD](https://github.com/yzd-v/MGD) or [cls_KD](https://github.com/yzd-v/cls_KD).
