### ISSUE TITLE
if i can use MultiScale training？

### ISSUE THREAD

**Issue by baibaidedongdong** [yzd-v/FGD#63]
Hello，if I use FGD in YOLOX， does it mean I can't use MultiScale in student model ？

**Comment by zhaotongdong** [comment]
If the student input size is 800, by 32 downsmple the size resaclse to 25, but the teacher model's feature map is 20, the size will not match

**Comment by yzd-v** [comment]
You can refer [yolox](https://github.com/yzd-v/FGD/blob/yolox/mmdet/distillation/distillers/detection_distiller.py) branch. It's OK to use multiscale.

**Comment by zhaotongdong** [comment]
> You can refer [yolox](https://github.com/yzd-v/FGD/blob/yolox/mmdet/distillation/distillers/detection_distiller.py) branch. It's OK to use multiscale.

thank you
