### ISSUE TITLE
FCOS训练及测试结果问题

### ISSUE THREAD

**Issue by Hwang64** [yzd-v/FGD#66]
作者你好，我使用FCOS框架进行蒸馏，发现训练过程中，随着epoch增加，测试结果在不断降低，不知道是不是配置的问题，能否帮帮忙看下？谢谢！

环境配置：
pytorch=1.7.1，mmdetection=2.11.0，mmcv=1.2.4，cuda=10.2

训练命令行：
bash tools/dist_train.sh configs/distillers/fgd/fgd_fcos_r101_distill_fcos_r50_2x_coco.py 2

训练log（只包含前5个epoch）：
[fgd_fcos.log](https://github.com/yzd-v/FGD/files/9670103/fgd_fcos.log)

**Comment by yzd-v** [comment]
你看一下你学生的config，和现在github代码里的代码是否有区别，因为mmdet升级的缘故，应该把原来的pretrained改掉到backbone的init，我这个代码是修改过的，你可能是clone的之前的config。你这个问题就是resnet50没有正确的加载到学生里去，正常训练下epoch 1的map是33左右

**Comment by yzd-v** [comment]
学生正确load resnet50时的warning应该是这样的，你可以比较下你的log里load res50时的报错
![image](https://user-images.githubusercontent.com/54797851/192921995-7582b703-f5a0-4c76-91a1-c263003a7788.png)

**Comment by Hwang64** [comment]
如果clone最新的mmdetection及FGD代码，除了readme中提到的替换和增加几个文件之外:
1. Add the configs/. in our codes to the configs/ in mmdetectin's codes.
2. Add the mmdet/distillation/. in our codes to the mmdet/ in mmdetectin's codes.
3. Replace the mmdet/apis/train.py and tools/train.py in mmdetection's codes with mmdet/apis/train.py and tools/train.py in our codes.

请问还有其他需要改动的吗？

**Comment by yzd-v** [comment]
大于2.12的版本，还需要修改这个
![image](https://user-images.githubusercontent.com/54797851/192990760-e2a46501-8bfc-462b-9313-b15d0b79bd17.png)
