### ISSUE TITLE
Should I change the mmdet/detectors/base.py when I train yolox?

### ISSUE THREAD

**Issue by baibaidedongdong** [yzd-v/FGD#67]
![1664420255465](https://user-images.githubusercontent.com/54987492/192928489-bd86720f-76ab-4a28-9613-581ff062adbd.png)
![1664420317663](https://user-images.githubusercontent.com/54987492/192928585-d82e6b20-3350-4b09-b4f7-1657dca0bcbc.png)
When student is training，it will carry out the filrst picture's step, if didn't change it, it will have some problem.

**Comment by yzd-v** [comment]
Please refer the whole yolox branch. You should change yolox.py instead of base.py.
