### ISSUE TITLE
Why the mAP is 0 when train myself data?

### ISSUE THREAD

**Issue by baibaidedongdong** [yzd-v/FGD#68]
![1664530977684](https://user-images.githubusercontent.com/54987492/193242657-66a5c54d-38de-4615-bbfc-ba0395f179ce.jpg)
![1664531008251](https://user-images.githubusercontent.com/54987492/193242762-9172c96e-9b96-4203-8a7c-779d6c7a8327.png)
Hello!When I train myself data, the loss is like this, but the mAP is 0, what reasons maybe cause such question?Thank you!

**Comment by yzd-v** [comment]
You can debug by yourself. I don't meet such problems.
