### ISSUE TITLE
为什么我运行的时候总提示 the model and loaded state dict do not match exactly?

### ISSUE THREAD

**Issue by chenqq1** [yzd-v/FGD#70]
是框架的问题吗？
missing keys in source state_dict: backbone.conv1.weight, backbone.bn1.weight, backbone.bn1.bias, backbone.bn1.running_mean, backbone.bn1.running_var, backbone.layer1.0.conv1.weight, backbone.layer1.0.bn1.weight, backbone.layer1.0.bn1.bias, backbone.layer1.0.bn1.running_mean,............

**Comment by tx19990922** [comment]
我有同样的问题，请问您解决了吗？

**Comment by chenqq1** [comment]
> 
是的，使用pth_transfer.py转换一下就好了。 use pth_transfer.py to transfer the model before testing. You can see it in README
