### ISSUE TITLE
mAP为0

### ISSUE THREAD

**Issue by baibaidedongdong** [yzd-v/FGD#71]
我在coco数据集上用yoloxm蒸馏yoloxs，损失曲线也正常，但是第一个epoch，精度为0，我已经按照reademe一步一步改了，之前是在自己数据集上精度为0，我想排查下到底哪里有问题，就在coco上进行了实验，发现在coco上也是同样问题。请问我这可能是哪里的问题那，已经困扰我很多天了。。。。
![1665288123524](https://user-images.githubusercontent.com/54987492/194737381-5ac7a141-ed63-434b-9d59-01ea50d2aa81.jpg)
![1665288158590](https://user-images.githubusercontent.com/54987492/194737398-e2f6bae4-5f81-45ba-a734-c8ebf154594f.png)
![1665288178548](https://user-images.githubusercontent.com/54987492/194737404-424a5449-5f27-4b8f-80b2-24d813c5775a.png)

**Comment by yzd-v** [comment]
我没遇到过这个情况，我只能帮你debug一下。训练中的测试使用的是simple下的self.student.simple_test，你可以试试把这改成self.teacher.simple_test，看看训练中eval是不是老师的精度。或者可以把训练完1轮的model进行transfer后，使用dist_test.sh进行推理一下，看看学生是否正确训练

**Comment by zhaotongdong** [comment]
我试过把训练好的student进行transfer结果同样为0，还没试用teacher预测，等下我试下看下结果



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Mesopotamia ***@***.***&gt;
发送时间: 2022年10月9日 12:11
收件人: yzd-v/FGD ***@***.***&gt;
抄送: baibaidedongdong ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yzd-v/FGD] mAP为0 (Issue #71)





 
我没遇到过这个情况，我只能帮你debug一下。训练中的测试使用的是simple下的self.student.simple_test，你可以试试把这改成self.teacher.simple_test，看看训练中eval是不是老师的精度。或者可以把训练完1轮的model进行transfer后，使用dist_test.sh进行推理一下，看看学生是否正确训练

**Comment by yzd-v** [comment]
还有两个你可以debug注意的点，1是你可以试试使用蒸馏框架，但不带蒸馏损失看看能不能正常训练。2是可能问题在于学生的初始化self.studnet.init_weights和train.py的model.init_weights()，不同版本mmdet使用的方法是不同的。

**Comment by zhaotongdong** [comment]
好的，谢谢指导



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Mesopotamia ***@***.***&gt;
发送时间: 2022年10月9日 12:26
收件人: yzd-v/FGD ***@***.***&gt;
抄送: baibaidedongdong ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [yzd-v/FGD] mAP为0 (Issue #71)





 
还有两个你可以debug注意的点，1是你可以试试使用蒸馏框架，但不带蒸馏损失看看能不能正常训练。2是可能问题在于学生的初始化self.studnet.init_weights和train.py的model.init_weights()，不同版本mmdet使用的方法是不同的。

**Comment by zhaotongdong** [comment]
> 还有两个你可以debug注意的点，1是你可以试试使用蒸馏框架，但不带蒸馏损失看看能不能正常训练。2是可能问题在于学生的初始化self.studnet.init_weights和train.py的model.init_weights()，不同版本mmdet使用的方法是不同的。

你好，我按照你说的做了2个实验：
1、第一个实验是让teacher去val，val的结果如下图，但是相比于直接预测val精度降低了，并且训练着第2个epoch相比于第一个epoch精度有变化，按理说不是应该没有变化吗；
![1665305262308](https://user-images.githubusercontent.com/54987492/194747233-36206390-6be7-4707-a470-5e8218beb21c.jpg)

2、用fgd的框架训练，但是不用fgd的loss，student能正常训练，但是精度依旧为0，下图是这个实验的的loss和结果，不知道什么原因导致的。。。我太菜了，希望能够指点指点，万分感谢；
![1665305313489](https://user-images.githubusercontent.com/54987492/194747274-6bfa3e2f-ff55-4fac-afaa-32717a7171ce.jpg)

**Comment by zhaotongdong** [comment]
> 还有两个你可以debug注意的点，1是你可以试试使用蒸馏框架，但不带蒸馏损失看看能不能正常训练。2是可能问题在于学生的初始化self.studnet.init_weights和train.py的model.init_weights()，不同版本mmdet使用的方法是不同的。

这个是用fgd的框架训练，但是不用fgd的loss的log
![1665305413952](https://user-images.githubusercontent.com/54987492/194747350-371f2254-f6ba-4e62-b980-05254586d302.jpg)

**Comment by yzd-v** [comment]
你试试这个框架蒸馏其他的模型，看看retinanet啥的有没有问题，还不行就重新clone设置代码把

**Comment by zhaotongdong** [comment]
> 你试试这个框架蒸馏其他的模型，看看retinanet啥的有没有问题，还不行就重新clone设置代码把

好的

**Comment by zhaotongdong** [comment]
> > 还有两个你可以debug注意的点，1是你可以试试使用蒸馏框架，但不带蒸馏损失看看能不能正常训练。2是可能问题在于学生的初始化self.studnet.init_weights和train.py的model.init_weights()，不同版本mmdet使用的方法是不同的。
> 
> 你好，我按照你说的做了2个实验： 1、第一个实验是让teacher去val，val的结果如下图，但是相比于直接预测val精度降低了，并且训练着第2个epoch相比于第一个epoch精度有变化，按理说不是应该没有变化吗； ![1665305262308](https://user-images.githubusercontent.com/54987492/194747233-36206390-6be7-4707-a470-5e8218beb21c.jpg)
> 
> 2、用fgd的框架训练，但是不用fgd的loss，student能正常训练，但是精度依旧为0，下图是这个实验的的loss和结果，不知道什么原因导致的。。。我太菜了，希望能够指点指点，万分感谢； ![1665305313489](https://user-images.githubusercontent.com/54987492/194747274-6bfa3e2f-ff55-4fac-afaa-32717a7171ce.jpg)

第一个实验精度下降我找到原因了，是因为下面
![1665306976344](https://user-images.githubusercontent.com/54987492/194748554-cc5e1e21-f5b3-46a2-89c7-117cbe85f19b.png)

![1665307045172](https://user-images.githubusercontent.com/54987492/194748607-a89e6654-4ae4-4c91-afda-093b6252f67f.png)

**Comment by zhaotongdong** [comment]
> 你试试这个框架蒸馏其他的模型，看看retinanet啥的有没有问题，还不行就重新clone设置代码把

你好，我用了retinanet试了fgd，训练正常，下面是前4epoch的结果；
![image](https://user-images.githubusercontent.com/54987492/194788669-e96f671c-c8ac-4452-814d-558550b0d8ab.png)

**Comment by yzd-v** [comment]
我也整不明白了 你来个完整log我看看

**Comment by zhaotongdong** [comment]
> 我也整不明白了 你来个完整log我看看

我的训练在服务器，不能下载才来。。。。

**Comment by yzd-v** [comment]
那你自己dubug一下吧，试试学生也像老师那样load一个训练好的模型进行初始化，看看能不能正常eval

**Comment by zhaotongdong** [comment]
> 模型进行初始化

这个我试过，也是0

**Comment by yzd-v** [comment]
我看issue其他同学是可以正常跑出来的，你从头整一下代码把，对齐mmdet和mmcv-full版本

**Comment by zhaotongdong** [comment]
> 我看issue其他同学是可以正常跑出来的，你从头整一下代码把，对齐mmdet和mmcv-full版本

好的，非常感谢

**Comment by yingwenmingzi123** [comment]
> 这个我试过，也是0
嗨，你最后改出来了吗，你用的哪个版本的mmdet和mmcv-full啊，用低版本的mmdet的话里面没有yolox算法，高版本的话会报sgd optimizer错误
