### ISSUE TITLE
Cascadercnn-resnet50蒸馏18,loss_fgd_fpn_0太大（第一张图）

### ISSUE THREAD

**Issue by Bingchuan521** [yzd-v/FGD#72]
![image](https://user-images.githubusercontent.com/115388511/194739677-11518c7a-12c5-47a5-9ed6-28e99903b919.png)

**Comment by Bingchuan521** [comment]
想问一下作者有遇到这种问题吗？谢谢

**Comment by Bingchuan521** [comment]
我的数据是15w张左右

**Comment by yzd-v** [comment]
第一个层级差这么多吗，你可以试试每个层级loss除以hw，进行一个loss尺度归一，我尝试过对精度没什么影响

**Comment by Bingchuan521** [comment]
而且这个上去的精度下降正常吗？

**Comment by Bingchuan521** [comment]
![Uploading image.png…]()

**Comment by Bingchuan521** [comment]
![image](https://user-images.githubusercontent.com/115388511/194740782-a16e58c0-bc3d-42e8-9f97-16949724f037.png)

**Comment by yzd-v** [comment]
这是X101-50的，你这个看起来不太正常
![image](https://user-images.githubusercontent.com/54797851/194740795-fa2c7a02-ed3e-49e4-ae1d-41b5fe1067d6.png)

**Comment by Bingchuan521** [comment]
其他三层看样子是对的，就这个0层不正常，但是处理方式都是一样的呀，你有没有什么好的建议

**Comment by yzd-v** [comment]
> 第一个层级差这么多吗，你可以试试每个层级loss除以hw，进行一个loss尺度归一，我尝试过对精度没什么影响

每个loss/这个层级的hw，均衡一下

**Comment by Bingchuan521** [comment]
而且这个刚上去训练我看精度下降在，正常吗？
