### ISSUE TITLE
Using fgd_retina_r101_fpn_2x_distill_retina_r50_fpn_2x_coco.py to find retina_ R50 distillation result AP is 37.3%?

### ISSUE THREAD

**Issue by wangtao2668129173** [yzd-v/FGD#75]
hi,Thanks for sharing your code,we  use the following installation packages respectively：
mmcv-full               1.3.17
mmdet                   2.11.0
I would like to ask if the above  version is too high and the function has changed, causing the teacher's model to fail to load with no exception.

**Comment by yzd-v** [comment]
The mAP is the same as the baseline. There may be something wrong with your codes. You can refer [MGD](https://github.com/yzd-v/MGD) for higher mmdet version.
