### ISSUE TITLE
Why does inference slow down with weights generated by FGD？

### ISSUE THREAD

**Issue by cmjkqyl** [yzd-v/FGD#76]
I use FGD to train retinanet_r50. The teacher network is retinanet_x101. Using the weights generated by pth_transfer.py to infer the original model will be about 10% slower than the weights obtained by direct training with the original model. I want to know why. THX！

**Comment by yzd-v** [comment]
It seems strange. The ckpt just include the weight's key and value. The ckpt obtained by distillation or trained directly are completely the same. You can aslo replace the value from the original model with that from the distillation model.
