### ISSUE TITLE
How Can I install mmdet 2.11.0 while its latest version is 2.28.1?

### ISSUE THREAD

**Issue by BonBon-Boom** [yzd-v/FGD#77]
In 2023, mmdetection is updated to 2.28.1,how can I install 2.11.0? Or when using higher version, which specific parts should I change, and how?

**Comment by yzd-v** [comment]
pip install mmdet==2.11.0 is fine. You can refer [MGD](https://github.com/yzd-v/MGD/tree/master/det) for higher version.
