### ISSUE TITLE
ConfigDict has no attribute "model"

### ISSUE THREAD

**Issue by truong11062002** [yzd-v/FGD#82]
After training FGD in our custom dataset, we already transferred in order to test it. But we got the error above. Is there any detail introduction in testing model? Thanks

**Comment by yzd-v** [comment]
Do you try [transfer](https://github.com/yzd-v/FGD/blob/master/pth_transfer.py)?

**Comment by truong11062002** [comment]
yes sure

**Comment by truong11062002** [comment]
I do my testing in mmdetection-distiller

**Comment by truong11062002** [comment]
root@3bbc6d017763:/mmdetection/data/Truong_Hai/mmdetection-distiller# CUDA_VISIBLE_DEVICES=0 python tools/test.py ../work_dirs/fgd_retina_rx101_64x4d_distill_retina_r50/fgd_retina_rx101_64x4d_distill_retina_r50.py ../new_model.pth --eval bbox --eval-options classwise=True
Traceback (most recent call last):
  File "tools/test.py", line 220, in <module>
    main()
  File "tools/test.py", line 126, in main
    cfg.model.pretrained = None
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/config.py", line 398, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/config.py", line 43, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'model'

**Comment by yzd-v** [comment]
You should use original student config for testing instead of distillation config.
![image](https://user-images.githubusercontent.com/54797851/224007567-2b8f3683-6875-4557-85a1-ec986680db8f.png)

**Comment by truong11062002** [comment]
Thank you so much for your help
