### ISSUE TITLE
请问作者有在yolov5上实现效果吗

### ISSUE THREAD

**Issue by yeweliang** [yzd-v/FGD#83]

**Comment by yeweliang** [comment]
我在yolov5的neck层，3层特征层使用FGD，但是还没有直接从数据中训练的好，代码直接使用的FeatureLoss，输入是yolov5预测的3层特征层

**Comment by yzd-v** [comment]
我没有实验过，但是其他人有实验过是有提升的，包括百度的[ppyoloe](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.6/configs/ppyoloe/distill)也成功使用了fgd，带来了提升，你可以参考一下。
