### ISSUE TITLE
hello，I want  to ask a question about yolox distillation

### ISSUE THREAD

**Issue by yingwenmingzi123** [yzd-v/FGD#85]
when I use a 2.11.0 version of mmdet, there is an error of yolox is not in the detector registry.
When I use a higher version of mmdet,I dont know how to revise the SGD optimizer. Can you help me to solve it? how to use your method  in yolox.

**Comment by yzd-v** [comment]
For mmdet < 3.0, refer this for [optimizer](https://github.com/yzd-v/FGD/blob/c03a6cf3b3cb3cbfd5554dbf4766e7135747d22d/mmdet/apis/train.py#L92)

**Comment by yingwenmingzi123** [comment]
I revised the optimizer，but  it still has error.
File "/home/yxy/anaconda3/envs/yolox/lib/python3.7/site-packages/mmdet/models/backbones/csp_darknet.py
patch_top_left = x[..., ::2,::2]
TypeError: string indices must be integers
But I use the  code to distill retinanet,there is no error.

**Comment by yzd-v** [comment]
Do you try yolox without distillation ? The error may in mmdet codes instead of distillation.

**Comment by yingwenmingzi123** [comment]
I try yolox without distillation ,there is no error. I used the version mmdet==2.19.0 and mmcv-full==1.5.0 ,  is it maybe related to mmdet and mmcv version mismatch?  Thank you for your reply.

**Comment by yzd-v** [comment]
Fine, I do not know how to fix it either.  You can run yolox, that means the mmdet and mmcv-full is matched.

**Comment by yingwenmingzi123** [comment]
```
        scale_y = 1.0
        scale_x = 1.0
        gt = kwargs['gt_bboxes']
        if self.yolox:
            scale_y = self.student._input_size[0] / self.student._default_input_size[0]
            scale_x = self.student._input_size[1] / self.student._default_input_size[1]
            student_loss, img, gt = self.student.forward_train(img, img_metas, **kwargs)
        else:
            student_loss = self.student.forward_train(img, img_metas, **kwargs)
        
        with torch.no_grad():
            fea_t = self.teacher.extract_feat(img)
```
您好，在in the mmdet/distillation/distillers/detection_distiller.py 这个文件里
当self.yolox is true, fea_t = self.teacher.extract_feat(img) 里面的img传入的实际并不是图像，而是loss_bbox. 
然后，您能看下，是不是这个问题导致输入的类型错误。但是当我改成student_loss = self.student.forward_train(img, img_metas, **kwargs)的时候，又会报下面的错误。但是我看代码里面有特征图对齐的代码，不知道这是怎么搞的了
`assert preds_S.shapel-2:] == preds_T.shapel-2:],'the output dim of teacher and student differ
AssertionError: the output dim of teacher and student differ`

**Comment by yzd-v** [comment]
返回的应该就是img，你看看你有没有对yolox这个[detetcor](https://github.com/yzd-v/FGD/blob/207473e830bb20ad589482211bf686d71686f6c2/mmdet/models/detectors/yolox.py#L101)做修改，这里执行forward_train后会返回loss, img, bbox
![image](https://user-images.githubusercontent.com/54797851/225851513-dee8ca40-303d-4b9c-a11f-2ec308b20c2d.png)

**Comment by xin-art** [comment]
> when I use a 2.11.0 version of mmdet, there is an error of yolox is not in the detector registry. When I use a higher version of mmdet,I dont know how to revise the SGD optimizer. Can you help me to solve it? how to use your method in yolox.

have you solved your problem?
