### ISSUE TITLE
invalid pre-training

### ISSUE THREAD

**Issue by cmjkqyl** [yzd-v/FGD#87]
I used ResNeXt-101 as the teacher network and ResNet-50 as the student network, and loaded their pre-trained weights on ImageNet on these two networks. But when I perform FGD on the VOC dataset, the training starts from the initialized weights. How to do pre-training?

mmdet==2.18
mmcv-full==1.3.14

**Comment by cmjkqyl** [comment]
Backbone config of student:
backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=-1,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch',
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50'))

Backbone config of teacher:
backbone=dict(
        type='ResNeXt',
        depth=101,
        groups=64,
        base_width=4,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=-1,
        norm_cfg=dict(type='BN', requires_grad=True),
        style='pytorch',
        init_cfg=dict(
            type='Pretrained', checkpoint='open-mmlab://resnext101_64x4d'))

**Comment by yzd-v** [comment]
Refer [Line37-47](https://github.com/yzd-v/FGD/blob/master/mmdet/distillation/distillers/detection_distiller.py#L37) for initialization.

**Comment by cmjkqyl** [comment]
I have set the value of init_student to False. When the model is trained on the VOC dataset for several epochs, the mAP is still lower than 10. Maybe this means that the pre-training weights have not been successfully loaded?

**Comment by cmjkqyl** [comment]
init_student=True or init_student=False, the same result.

**Comment by yzd-v** [comment]
something is wrong with the initialization. you can refer this and learn about how the distillation works. It will help you to debug this. I can only help you to solve the problem with FGD.

**Comment by yzd-v** [comment]
![image](https://github.com/yzd-v/FGD/assets/54797851/11044f0d-bcfb-4cf8-9109-14ce494f57d3)

**Comment by cmjkqyl** [comment]
Thank you for your help!
