### ISSUE TITLE
Can the network be replicated using the 2023 version of mmdetection?

### ISSUE THREAD

**Issue by kiven228** [yzd-v/FGD#89]
I tried using the latest version of mmdet for reproduction, but I found that there are many more things in this version compared to before. Has anyone successfully reproduced it?

**Comment by yzd-v** [comment]
yes, you can refer [cls_kd](https://github.com/yzd-v/cls_KD/tree/1.0) for classification. This is with mmengine.

**Comment by kiven228** [comment]
Thank you for your answer. I have read your code in its entirety and have some questions. The distillation network does indeed calculate distillation losses for the global and focused features between the student model and the teacher model, but specifically, how does the student model obtain these features for prediction? For example, in using GCBLOCK to extract global features, how does the student network utilize global features on itself for prediction? I only saw the code with the ability to calculate distillation losses.Looking forward to your reply and thanks again!

**Comment by yzd-v** [comment]
After distillation, we do not need the gcblock actually. The global features are just used for distillation instead of prediction.

**Comment by kiven228** [comment]
Does it mean that the student network did not use the extracted global features during the training process? Because I have seen how to extract and distill global or attention features, but I have not found how the extracted features are transmitted to the network for use. Thank you for taking the time to answer.
