### ISSUE TITLE
How to output the Params or FLOPs after FGD distillation?

### ISSUE THREAD

**Issue by chenqqqqqqq** [yzd-v/FGD#92]
In order to compare with the student model, how to output the Params or FLOPs after FGD distillation?

**Comment by yzd-v** [comment]
The params and flops keep the same as the student. What do you mean?

**Comment by chenqqqqqqq** [comment]
> The params and flops keep the same as the student. What do you mean?

Because I watched the weight file size get a lot smaller, I thought there would be fewer parameters as well. Will the model FPS improve after distillation?

**Comment by chenqqqqqqq** [comment]
> The params and flops keep the same as the student. What do you mean?

I just tested it using the get_flops in mmdetection, and the FPS has basically not improved. Is this situation normal?

**Comment by yzd-v** [comment]
Distillation would not change the params or flops of the student model, which is used to infer. The speed will also keep the same. The weight file gets smalled because we delete the optimizer params.

**Comment by chenqqqqqqq** [comment]
> Distillation would not change the params or flops of the student model, which is used to infer. The speed will also keep the same. The weight file gets smalled because we delete the optimizer params.

Okay, got it
