### ISSUE TITLE
你好，我看到您在GitHub更新了yolox的相关蒸馏的数据

### ISSUE THREAD

**Issue by Northcandle** [yzd-v/FGD#94]
可以麻烦您在Git仓库中更新一下yolox相关的config文件吗

**Comment by CoffeeinTeaC** [comment]
您好，可以麻烦您在Git仓库中更新一下yolox相关的config文件吗

**Comment by yzd-v** [comment]
这里有一个yolox的[config](https://github.com/yzd-v/FGD/blob/yolox/configs/distillers/fgd/fgd_yoloxl_distill_yoloxm_coco.py)啊

**Comment by CoffeeinTeaC** [comment]
> 这里有一个yolox的[config](https://github.com/yzd-v/FGD/blob/yolox/configs/distillers/fgd/fgd_yoloxl_distill_yoloxm_coco.py)啊

我的意思是student_cfg = 'configs/yolox/yolox_m_8x8_300e_coco.py'
teacher_cfg = 'configs/yolox/yolox_l_8x8_300e_coco.py'   这两个py脚本的

**Comment by yzd-v** [comment]
这个文件在原来的mmdetection里面，找到对应版本复制过来就可
